name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Create MIME type configuration
        run: |
          echo '{ "*.js": "application/javascript", "*.jsx": "application/javascript", "*.mjs": "application/javascript", "*.json": "application/json" }' > ./dist/_headers
          echo '/* /index.html 200' > ./dist/_redirects
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
